/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export declare class BigIntArbitrary {

}

export declare class BooleanArbitrary {

}

export declare class DateArbitrary {

}

export declare class DoubleArbitrary {

}

export declare class FloatArbitrary {

}

export declare class IntegerArbitrary {

}

export declare class MaxSafeIntegerArbitrary {

}

export declare class MaxSafeNatArbitrary {

}

export declare class NatArbitrary {

}

export declare class StringArbitrary {

}

export declare class TupleArbitrary {

}

export declare function bigint(min?: bigint | undefined | null, max?: bigint | undefined | null): ExternalObject<BigIntArbitrary>

export declare function boolean(): ExternalObject<BooleanArbitrary>

export interface DateOption {
  min?: Date
  max?: Date
  noInvalidDate?: boolean
}

export declare function double(option: DoubleOption): ExternalObject<DoubleArbitrary>

export interface DoubleOption {
  min?: number
  max?: number
  minExcluded?: boolean
  maxExcluded?: boolean
  noDefaultInfinity?: boolean
  noDefaultNan?: boolean
  noInteger?: boolean
}

export declare function float(option: FloatOption): ExternalObject<FloatArbitrary>

export interface FloatOption {
  min?: number
  max?: number
  minExcluded?: boolean
  maxExcluded?: boolean
  noDefaultInfinity?: boolean
  noDefaultNan?: boolean
  noInteger?: boolean
}

export declare function integer(option?: IntegerOption | undefined | null): ExternalObject<IntegerArbitrary>

export interface IntegerOption {
  min?: number
  max?: number
}

export declare function maxSafeInteger(): ExternalObject<MaxSafeIntegerArbitrary>

export declare function maxSafeNat(): ExternalObject<MaxSafeNatArbitrary>

export declare function nat(option?: NatOption | undefined | null): ExternalObject<NatArbitrary>

export interface NatOption {
  max?: number
}

export type PrimitiveArbs<> =
  ExternalObject<BooleanArbitrary> | ExternalObject<BigIntArbitrary> | ExternalObject<IntegerArbitrary> | ExternalObject<NatArbitrary> | ExternalObject<MaxSafeIntegerArbitrary> | ExternalObject<MaxSafeNatArbitrary> | ExternalObject<StringArbitrary> | ExternalObject<FloatArbitrary> | ExternalObject<DoubleArbitrary> | ExternalObject<DateArbitrary>

export type PrimitiveValues =
  any

export declare function string(option?: StringOption | undefined | null): ExternalObject<StringArbitrary>

export interface StringOption {
  unit?: StringUnit
  minLength?: number
  maxLength?: number
  size?: number
}

export declare const enum StringUnit {
  Ascii = 0,
  Unicode = 1,
  Grapheme = 2,
  GraphemeComposite = 3,
  GraphemeAscii = 4,
  BinaryAscii = 5
}

export declare function tuple(arbs: Array<PrimitiveArbs>): TupleArbitrary
