/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function boolean(): boolean

export interface DoubleOption {
  min?: number
  max?: number
  minExcluded?: boolean
  maxExcluded?: boolean
  noDefaultInfinity?: boolean
  noDefaultNan?: boolean
  noInteger?: boolean
}

export declare function float(option: FloatOption): number

export interface FloatOption {
  min?: number
  max?: number
  minExcluded?: boolean
  maxExcluded?: boolean
  noDefaultInfinity?: boolean
  noDefaultNan?: boolean
  noInteger?: boolean
}

export declare function integer(option: IntegerOption): number

export interface IntegerOption {
  min?: number
  max?: number
}

export declare function maxSafeInteger(): number

export declare function maxSafeNat(): number

export declare function nat(option: NatOption): number

export interface NatOption {
  max?: number
}
