/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class DoubleArbitrary {

}

export declare class FloatArbitrary {

}

export declare class IntegerArbitrary {

}

export declare class MaxSafeIntegerArbitrary {

}

export declare class MaxSafeNatArbitrary {

}

export declare class NatArbitrary {

}

export declare class StringArbitrary {

}

export declare function boolean(): boolean

export declare function double(option: DoubleOption): DoubleArbitrary

export interface DoubleOption {
  min?: number
  max?: number
  minExcluded?: boolean
  maxExcluded?: boolean
  noDefaultInfinity?: boolean
  noDefaultNan?: boolean
  noInteger?: boolean
}

export declare function float(option: FloatOption): FloatArbitrary

export interface FloatOption {
  min?: number
  max?: number
  minExcluded?: boolean
  maxExcluded?: boolean
  noDefaultInfinity?: boolean
  noDefaultNan?: boolean
  noInteger?: boolean
}

export declare function integer(option?: IntegerOption | undefined | null): IntegerArbitrary

export interface IntegerOption {
  min?: number
  max?: number
}

export declare function maxSafeInteger(): MaxSafeIntegerArbitrary

export declare function maxSafeNat(): MaxSafeNatArbitrary

export declare function nat(option?: NatOption | undefined | null): NatArbitrary

export interface NatOption {
  max?: number
}

export declare function string(option: StringOption): StringArbitrary

export interface StringOption {
  unit?: StringUnit
  minLength?: number
  maxLength?: number
  size?: number
}

export declare const enum StringUnit {
  Ascii = 0,
  Unicode = 1,
  Grapheme = 2,
  GraphemeComposite = 3,
  GraphemeAscii = 4,
  BinaryAscii = 5
}
